---
title: "Replication project - 5 - Final Logistic Regression - T1DM vs controls - SGSS"
output:
  html_document: default
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "output") })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(furniture)
library(knitr)
library(here)

# Recommended best practice - clears all values from the environment
rm(list = ls())
```

```{r load data, echo=FALSE}
t1dm_df <- readRDS(file=here("data", "processed-t1d_df_sgss_eth.rds"))
t1dm_df1 <- t1dm_df %>% dplyr::filter(diab==1)
```

## Logistic regression models

Finally, we ran a logistic model for 28 day admission following covid diagnosis adjusting for age, sex, diabetes, hba1c, BMI, Age, ethnicity and townsend. 

***NB this is using the SGSS data to determine COVID tests***

```{r , echo=FALSE, warning=FALSE, message = FALSE}


fit <- glm(admission ~ age + Sex + as.factor(diab) + LatestBMIValue  + LatestEGFRValue +
             ethnicity + TownsendScoreHigherIsMoreDeprived + as.factor(PatientHasHYPERTENSION) + as.factor(PatientHasASTHMA) + as.factor(PatientHasCOPD) + as.factor(PatientHasSMI), data = t1dm_df, family = "binomial")


diab1_coef_full <- data.frame(Var = c("Intercept", "Age", "Sex-M", "Diabetes", "BMI", "eGFR", "ethnicity-African", 
                                    "Ethnicity-Asian", "Ethnicity-Mixed", "Ethnicity-Other", "Townsend", "Hypertension", "Asthma", "COPD", "SMI"), 
                         cbind(OR = exp(coef(fit)), exp(confint(fit)) ))


kable(diab1_coef_full, digits = 3, row.names = FALSE, align = "lccc", caption = "Diabetes coefficient from full adjusted logistic model in T1Ds matched cohort - using SGSS for COVID tests" )
```
